server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true  # true
    fetch-registry: true  # true
    service-url:
      defaultZone: http://j8b306.p.ssafy.io:8761/eureka  # http://localhost:8761/eureka #


spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
#         show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j8b306.p.ssafy.io:3306/booklet_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: booklet
    password: qnrwjrqnrwjr!qnrfpt
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/booklet_db?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: bms1226@
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher